### ISSUE TITLE
DiNo generates invalid C++ code for domain 1D-powered-descent

### ISSUE THREAD

**Issue by miquelramirez** [KCL-Planning/DiNo#2]
Hello,

after working my way around the issue with `flex` (downgrading to 2.5.39 from 2.6) I have stumbled onto another issue.

Invoking `DiNo` like this 

```
DiNo/ex/1D-powered-descent$ ../../bin/dino descent.pddl prob_earth01.pddl --custom 1.0 5 2 --clean --force
```

on the first instance of the 1D Powered Descent domain results in generating invalid C++ code in the file `descent.cpp`, output of g++ below

```
Compiling executable planner, please wait...
descent.cpp:630:1: error: stray ‘\360’ in program
 {�x}
 ^
descent.cpp:630:1: error: stray ‘\37’ in program
descent.cpp:630:1: error: stray ‘\1’ in program
descent.cpp: In member function ‘void world_class::fire_processes_plus()’:
descent.cpp:617:22: error: ‘mQ’ was not declared in this scope
   mu_thrust_clock = (mQ}
                      ^
descent.cpp:617:24: error: expected ‘)’ before ‘}’ token
   mu_thrust_clock = (mQ}
                        ^
descent.cpp:621:39: error: qualified-id in declaration before ‘(’ token
 void world_class::fire_processes_minus()
                                       ^
In file included from /home/bowman/Sandboxes/DiNo/bin/../include/upm_epilog.hpp:49:0,
                 from descent.cpp:4220:
/home/bowman/Sandboxes/DiNo/bin/../include/upm_verifier.cpp:44:1: error: expected ‘}’ at end of input
 }
 ^
```

See [attached & compressed](https://github.com/KCL-Planning/DiNo/files/525999/descent.zip) generated sourcefile.

It **looks** to me like DiNo code generator is writing a pointer to a buffer instead of the contents of the buffer. 

**NOTE**: I am testing this on a 64-bit system, not sure if this is relevant but since I saw `g++-multilib` as a dependency  it may be.

Cheers,

Miquel.

**Comment by miquelramirez** [comment]
Here's a tentative fix for this issue:

https://github.com/KCL-Planning/DiNo/pull/3

**Comment by wmp9** [comment]
Fixed
